image: node:8

cache:
  paths:
    - node_modules/

before_script:
  - yarn

pages:
  stage: deploy
  script:
    - yarn --noprogress build
  artifacts:
    paths:
      - public
  only:
    - master
